Repository Wanted-Pre-Onboarding-Android-team3-2/android-wanted-SensorDashboardApp, pull requests merged in 2022-09, with the labels that each got.

#2 Feat/setup project
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/sensordashboard/MainActivity.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/SensorApplication.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/base/BaseFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/base/BaseViewModel.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/constant/Constants.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/di/DataSourceModule.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/di/DatabaseModule.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/di/RepositoryModule.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/extension/ExampleExtension.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/util/ExampleUtil.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/SensorHistoryDatabase.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/dao/SensorHistoryDao.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/datasource/SensorHistoryLocalDataSource.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/datasourceimpl/SensorHistoryLocalDataSourceImpl.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/entity/SensorHistory.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/repositoryimpl/SensorHistoryRepositoryImpl.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/model/SensorHistory.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/repository/SensorHistoryRepository.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/usecase/DeleteSensorHistoryUseCase.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/usecase/GetSensorHistoryListUseCase.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/usecase/SaveSensorHistoryUseCase.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/adapter/NavigationBindingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/MainActivity.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_list/SensorHistoryListFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_play/SensorHistoryPlayFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_show/SensorHistoryShowFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryMeasureViewModel.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_sensor_history_list.xml
  app/src/main/res/layout/fragment_sensor_history_measure.xml
  app/src/main/res/layout/fragment_sensor_history_play.xml
  app/src/main/res/layout/fragment_sensor_history_show.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: chore, feature, ui, DONE, 영진 :unicorn:

#8 [ADD] Hilt - SensorModule 추가
  app/src/main/java/com/preonboarding/sensordashboard/common/di/SensorModule.kt
Labels: refactor, IN PROGRESS, 영진 :unicorn:

#10 [Feat] Sensor
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/sensordashboard/common/SensorApplication.kt
  app/src/main/java/com/preonboarding/sensordashboard/common/di/SensorModule.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/model/SensorHistory.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/MainActivity.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryMeasureViewModel.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_sensor_history_measure.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feature, IN PROGRESS, 준성 :unicorn:, 현수 :unicorn:

#15 [FEAT] 화면 이동 구현
  app/src/main/java/com/preonboarding/sensordashboard/common/constant/Constants.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/adapter/NavigationBindingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/MainActivity.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_list/SensorHistoryListFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_play/SensorHistoryPlayFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_show/SensorHistoryShowFragment.kt
  app/src/main/res/drawable/ic_arrow_back_24.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_sensor_history_list.xml
  app/src/main/res/layout/fragment_sensor_history_measure.xml
  app/src/main/res/layout/fragment_sensor_history_play.xml
  app/src/main/res/layout/fragment_sensor_history_show.xml
  app/src/main/res/navigation/main_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: feature, ui, DONE, 영진 :unicorn:

#18 [FEAT] 그래프 데이터 뷰모델 통합관리
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/preonboarding/sensordashboard/common/constant/Constants.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/model/MeasureValue.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/adapter/GraphBindingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryMeasureViewModel.kt
  app/src/main/res/layout/fragment_sensor_history_measure.xml
  build.gradle
  settings.gradle
Labels: feature, refactor, IN PROGRESS, TODO, 현수 :unicorn:

#16 [FEAT] 히스토리 리스트 리사이클러뷰 구현
  app/src/main/java/com/preonboarding/sensordashboard/data/local/dao/SensorHistoryDao.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/datasource/SensorHistoryLocalDataSource.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/datasourceimpl/SensorHistoryLocalDataSourceImpl.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/entity/SensorHistoryEntity.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/paging/HistoryPagingSource.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/repositoryimpl/SensorHistoryRepositoryImpl.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/repository/SensorHistoryRepository.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/usecase/GetSensorHistoryListUseCase.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_list/HistoryPagingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_list/SensorHistoryListFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryViewModel.kt
  app/src/main/res/layout/fragment_sensor_history_list.xml
  app/src/main/res/layout/item_history_rv.xml
  app/src/main/res/values/strings.xml
Labels: feature, ui, IN PROGRESS, 유리 :unicorn:

#19 Feat/센서 데이터 저장
  app/build.gradle
  app/src/main/java/com/preonboarding/sensordashboard/data/local/HistoryTypeConverter.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/SensorHistoryDatabase.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/local/entity/SensorHistoryEntity.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/model/SensorHistory.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/MainActivity.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryMeasureViewModel.kt
  app/src/main/res/values/style.xml
  settings.gradle
Labels: feature, IN PROGRESS, TODO, 준성 :unicorn:

#20 [FEAT] 측정하기 UI 및 데이터 흐름 구현
  app/src/main/java/com/preonboarding/sensordashboard/common/extension/ExampleExtension.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/adapter/GraphBindingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryMeasureViewModel.kt
  app/src/main/res/drawable/bg_button_selected.xml
  app/src/main/res/drawable/bg_button_unselected.xml
  app/src/main/res/layout/fragment_sensor_history_measure.xml
  app/src/main/res/values/colors.xml
Labels: feature, fix, DONE, 현수 :unicorn:

#22 [FEAT] 세 번째 페이지 구현
  app/src/main/java/com/preonboarding/sensordashboard/presentation/adapter/NavigationBindingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_play/SensorHistoryPlayFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_play/SensorHistoryPlayViewModel.kt
  app/src/main/res/drawable/ic_play_48.xml
  app/src/main/res/drawable/ic_stop_48.xml
  app/src/main/res/layout/fragment_sensor_history_list.xml
  app/src/main/res/layout/fragment_sensor_history_play.xml
  app/src/main/res/layout/item_history_rv.xml
  app/src/main/res/navigation/main_graph.xml
Labels: feature, ui, DONE, 정호 :unicorn:

#23 [FEAT] X, Y, Z 좌표 추가
  app/src/main/java/com/preonboarding/sensordashboard/presentation/adapter/GraphBindingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_play/SensorHistoryPlayViewModel.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_show/SensorHistoryShowFragment.kt
  app/src/main/res/layout/fragment_sensor_history_measure.xml
  app/src/main/res/layout/fragment_sensor_history_play.xml
  app/src/main/res/layout/fragment_sensor_history_show.xml
  app/src/main/res/layout/item_history_rv.xml
Labels: feature, ui, DONE, 정호 :unicorn:

#24 [FIX] 페이징 리스트 반영 수정
  app/src/main/java/com/preonboarding/sensordashboard/data/local/datasourceimpl/SensorHistoryLocalDataSourceImpl.kt
  app/src/main/java/com/preonboarding/sensordashboard/data/repositoryimpl/SensorHistoryRepositoryImpl.kt
  app/src/main/java/com/preonboarding/sensordashboard/domain/model/SensorHistory.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/adapter/GraphBindingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/MainActivity.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_list/HistoryPagingAdapter.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_list/SensorHistoryListFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/view/sensor_history_measure/SensorHistoryMeasureFragment.kt
  app/src/main/java/com/preonboarding/sensordashboard/presentation/viewmodel/SensorHistoryViewModel.kt
  app/src/main/res/layout/item_history_rv.xml
Labels: fix, DONE, 현수 :unicorn:
